# Generated by Django 4.2.2 on 2023-06-07 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=0, upload_to='main_photos/', verbose_name='Фото')),
                ('title', models.CharField(max_length=100, verbose_name='Вид номера')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.SmallIntegerField(default=0, verbose_name='Цена за сутки')),
                ('price_2', models.SmallIntegerField(default=0, verbose_name='Цена за сутки с завтраком')),
                ('url', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(upload_to='room_photos/', verbose_name='Фото')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'Фото номеров',
            },
        ),
    ]
