# Generated by Django 4.2.2 on 2023-06-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='enable',
            field=models.SmallIntegerField(default=0, verbose_name='Сколько номеров данного типа свободно'),
        ),
    ]
