# Generated by Django 4.2.2 on 2023-06-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_room_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='details',
            field=models.TextField(default='', verbose_name='Детали'),
        ),
    ]
